### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by nicjp** [miqid/atom-rustsym#4]
After updating to the latest version of Atom (1.21.0) I received the following error with rustsym loaded:

### Stack Trace

Failed to activate the rustsym package

```
At Cannot read property 'name' of undefined

TypeError: Cannot read property 'name' of undefined
    at /packages/rustsym/lib/main.js:74:34
    at Array.find (native)
    at prioritizeCommandListener (/packages/rustsym/lib/main.js:71:28)
    at Package.updateOverrideCommands (/packages/rustsym/lib/main.js:102:3)
    at Package.activate (/packages/rustsym/lib/main.js:23:38)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
api-workbench 0.8.47 
ascii-hex 0.2.0 
atom-beautify 0.30.5 
atom-ide-ui 0.4.0 
atom-language-rust 0.12.3 
atom-yamljson 0.2.4 
autocomplete-racer 0.1.3 
autocomplete-ruby 0.2.8 
build-cargo 2.0.0 
busy-signal 1.4.3 
file-types 0.5.5 
gitignore-snippets 0.2.5 
intentions 1.1.5 
json-schema 0.1.15 
language-ada 1.1.0 
language-api-blueprint 1.0.2 
language-cshtml 0.3.0 
language-icinga2 0.3.0 
language-powershell 4.0.0 
language-rust 0.4.12 
linter 2.2.0 
linter-api-blueprint 0.4.0 
linter-json-lint 0.1.2 
linter-ruby 1.2.6 
linter-rust 0.8.0 
linter-swagger 0.4.2 
linter-ui-default 1.6.10 
project-manager 3.3.5 
racer 0.20.0 
ruby-block 0.3.6 
rust-api-docs-helper 0.5.1 
rustfmt 0.1.3 
rustsym 0.4.0 
tokamak 0.4.0 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
```

Details of the environment:
**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [rustsym](https://github.com/miqid/atom-rustsym) package 0.4.0

**Comment by nicjp** [comment]
Looks like this and #5 are the same error.

**Comment by ghost** [comment]
Thanks for the error report.

I've made a fix to address this problem in the next release ([0.4.1](https://github.com/miqid/atom-rustsym/releases/tag/v0.4.1)). If you're still experiencing loading problems, please re-open this issue with additional information.
